config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  dp "Debug print by aoyama"
  dp ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  post 'inquiries/confirm'
  get  'inquiries/thank'
  resources :inquiries, only: [:new, :create]

  resources :tests

  root 'tests#index'

  #namespace :admin do
  #  resources :inquiries, only: [:index, :edit, :update, :destroy]
  #end

  namespace :backend do
    root to: "products#index"
    resources :products
    resources :widgets
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend/application_controller.rb
# Backend::内全てのコントローラの基底
class Backend::ApplicationController < ActionController::Base
end

app/controllers/backend/products_controller.rb
# 製品のコントローラ
class Backend::ProductsController < Backend::ResourceController
end

app/controllers/backend/resource_controller.rb
# リソースに関連するコントローラの基底
class Backend::ResourceController < Backend::ApplicationController
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]


  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    if not params[:cancel].nil?
      @inquiry = Inquiry.new(inquiry_params)
      render :new
      return
    end

    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to inquiries_thank_path, notice: '正常に保存できました' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)

  end

  def thank

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :body)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  def sage(*args)
    puts "\e[7m\e[31m" + caller.first + "\e[0m"
    args.each {|a| ap a}
    puts
  end

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
    sage [1, 2, 3]
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:name, :flag, :salary, :birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # 改行コードを<br />タグに変換
    def nl2br(str)
        str = html_escape(str)
        str.gsub(/\r\n|\r|\n/, "<br />").html_safe
    end
end

app/helpers/backend/application_helper.rb
module Backend::ApplicationHelper
end

app/helpers/backend/products_helper.rb
module Backend::ProductsHelper
end

app/helpers/backend/resource_helper.rb
module Backend::ResourceHelper
  def attributes
    resource_class.attribute_names - %w(id created_at updated_at)
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/inquiries.bak/_form.html.erb
<%= form_for(@inquiry, url: admin_inquiry_path) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
	  <tr>
		  <th>名前</th>
		  <td>
			  <%= f.text_field :name %>
		  </td>
	  </tr>
	  <tr>
		  <th>E-mail</th>
		  <td><%= f.email_field :email %></td>
	  </tr>
	  <tr>
		  <th>内容</th>
		  <td><%= f.text_area :body %></td>
	  </tr>
  </table>

  <div class="actions">
    <%= f.submit '保存' %>
  </div>
<% end %>

app/views/admin/inquiries.bak/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '一覧画面へ戻る', admin_inquiries_path %>

app/views/admin/inquiries.bak/index.html.erb
<p id="notice"><%= notice %></p>

<h1>お問い合わせ一覧画面</h1>

<table>
  <thead>
    <tr>
		<th>
			ID
		</th>
		<th>
			日時
		</th>
		<th>
			E-mail
		</th>
		<th>
			名前
		</th>
		<th>

		</th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
		  <td>
			  <%= inquiry.id %>
		  </td>
		  <td>
			  <%= inquiry.name %>
		  </td>
		  <td>
			  <%= inquiry.email %>
		  </td>
		  <td>
			  <%= inquiry.created_at.strftime('%Y年%m月%d日') %>
		  </td>
		  <td>
			<%= link_to '編集', edit_admin_inquiry_path(inquiry) %><br>
			<%= link_to '削除', admin_inquiry_path(inquiry.id), method: :delete, data: { confirm: 'Are you sure?' } %><br>
		  </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ホーム', root_path %>
<%= link_to 'お問い合わせ入力画面', new_inquiry_path %>

app/views/admin/inquiries.bak/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/admin_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか？", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backend/resource/index.html.haml
<%= render "index", attributes: attributes %>

app/views/inquiries/_form.html.erb
<%= form_for(@inquiry, url: inquiries_confirm_path) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
	  <tr>
		  <th>名前</th>
		  <td>
			  <%= f.text_field :name %>
		  </td>
	  </tr>
	  <tr>
		  <th>E-mail</th>
		  <td><%= f.email_field :email %></td>
	  </tr>
	  <tr>
		  <th>内容</th>
		  <td><%= f.text_area :body %></td>
	  </tr>
  </table>

  <div class="actions">
    <%= f.submit '確認画面へ' %>
  </div>
<% end %>

app/views/inquiries/confirm.html.erb
<h1>お問い合わせ　確認画面</h1>

<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
	  <tr>
		  <th>名前</th>
		  <td>
			  <%= @inquiry.name %>
			  <%= f.hidden_field :name %>
		  </td>
	  </tr>
	  <tr>
		  <th>E-mail</th>
		  <td>
			  <%= @inquiry.email %>
			  <%= f.hidden_field :email %>
		  </td>
	  </tr>
	  <tr>
		  <th>内容</th>
		  <td>
			  <%= nl2br(@inquiry.body) %>
			  <%= f.hidden_field :body %>
		  </td>
	  </tr>
  </table>

  <div class="actions">
    <%= f.submit 'キャンセル', name: 'cancel' %>
    <%= f.submit '送信', name: 'commit' %>
  </div>
<% end %>

app/views/inquiries/new.html.erb
<h1>お問い合わせ　入力画面</h1>

<%= render 'form' %>

<%= link_to 'ホーム', root_path %>

app/views/inquiries/thank.html.erb
<h1>お問い合わせ　完了画面</h1>

<p id="notice"><%= notice %></p>

<p>
	お問い合わせありがとうございました。
</p>

<%= link_to 'ホーム', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>問い合わせフォームのサンプル</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container2">
		<!-- erb -->
		<% if notice.present? %>
		<p class="notice"><%= notice %></p>
		<% end %>
		<% if alert.present? %>
		<p class="alert"><%= alert %></p>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>